# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20180116_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
